version: '3.1'

services:
  db:
    image: postgis/postgis:14-3.2-alpine
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - PGDATA=/var/lib/postgresql/data/db
    volumes:
      - ./data:/var/lib/postgresql/data
    command: postgres -c max_wal_senders=0 -c max_wal_size=10240 -c wal_level=minimal -c random_page_cost=1.1

  adminer:
    image: adminer
    ports:
      - 8080:8080
