version: '3.1'

services:
  db:
    image: postgis/postgis:14-3.2-alpine
    container_name: postgis
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - PGDATA=/var/lib/postgresql/data/db
    volumes:
      - ./data:/var/lib/postgresql/data
    command: postgres -c max_wal_senders=0 -c max_wal_size=10240 -c wal_level=minimal -c random_page_cost=1.1

  adminer:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    ports:
      - 8080:80
