version: '3.1'

services:
  db:
    image: postgis/postgis
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_PASSWORD

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
