version: '3.7'

services:
  db:
    image: postgis/postgis:14-3.2-alpine
    container_name: postgis
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - PGDATA=/var/lib/postgresql/data/db
    volumes:
      - ./data:/var/lib/postgresql/data
      # comment/remove bellow volumes after seeding is done
      - ./apps/covis-service/seed.sql:/var/lib/postgresql/data/seed.sql
      - ./apps/covis-service/src/assets/data.csv.gz:/var/lib/postgresql/data/data.csv.gz
    command: postgres -c max_wal_senders=0 -c max_wal_size=10240 -c wal_level=minimal -c random_page_cost=1.1
    restart: on-failure

  service:
    image: covis-service
    container_name: covis-service
    depends_on:
      - db
    environment:
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_HOST=db
    ports:
      - 3000:3000
    restart: on-failure

  app:
    image: covis-app
    container_name: covis-app
    environment:
      - BACKEND_URL=http://service:3000
    ports:
      - 80:80
    restart: on-failure
