version: '3.1'

services:
  mongo:
    image: mongo
    container_name: mongo
    ports:
      - ${MONGODB_PORT}:27017
    volumes:
      - ./data:/data
    environment:
      MONGO_INITDB_ROOT_USERNAME: "${MONGODB_USER}"
      MONGO_INITDB_ROOT_PASSWORD: "${MONGODB_PASSWORD}"

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    depends_on:
      - mongo
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: "${MONGODB_USER}"
      ME_CONFIG_MONGODB_ADMINPASSWORD: "${MONGODB_PASSWORD}"
      ME_CONFIG_MONGODB_URL: mongodb://${MONGODB_USER}:${MONGODB_PASSWORD}@mongo:${MONGODB_PORT}/
